version: "3.8"

services:
  api:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=flaskdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data:
