default_region               = "us-east-1"
docker_username              = "matlau"
github_username              = "MatthewCYLau"
github_project_name          = "python-flask-aws-terraform"
app_name                     = "python-flask-app"
environment                  = "staging"
postgres_password_secret_arn = "arn:aws:secretsmanager:us-east-1:830663695860:secret:RDSPostgresPassword-5p1A4P"